# Generated by Django 4.1.3 on 2022-12-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cetegory',
            new_name='category',
        ),
    ]
